### ISSUE TITLE
NID DB validator

### ISSUE THREAD

**Issue by devnoname120** [vitasdk/vita-headers#100]
~- [ ] Write a [JSON schema](https://github.com/vitasdk/vita-headers/issues/83#issuecomment-261812931)~
- [ ] Write a [YAML schema](https://github.com/Grokzen/pykwalify)
- [ ] Make the current database compliant
- [ ] Add it to Travis so that every pull request gets verified

**Comment by d3m3vilurr** [comment]
actually we need migrator before writing validator.
anyway i want to discuss about json schema.

jsonschema module is non standard extra packages, so someone cannot want to install this.
IMO, db.json format is simple. why we select sledgehammer for this?

**Comment by devnoname120** [comment]
I think that @frangarcj has already built a migrator.

Well, by defining a specification we can define precisely what we expect. If there is something wrong, the validator will tell us exactly what's wrong and where. This should make it more useful than a basic script checking for a few things.

**Comment by d3m3vilurr** [comment]
> I think that @frangarcj has already built a migrator.

ok

> Well, by defining a specification we can define precisely what we expect. If there is something wrong, the validator will tell us exactly what's wrong and where. This should make it more useful than a basic script checking for a few things.

actually my word is just asking why we select more dependencies instead minimalism.
really thought you to need schema in db.json?
if our spec is already too complex, in my opinion, that is already wrong.

why we select json? in before, member said it's simple, porting easier, and else, whatever.
i'm one of hater of the javascript community :/
but yeah i agree, json spec is actually nice. but it's just little old.
(this format actually not modified since first introduce)

but json-schema spec is more weird. it defined for define, and looks mess.
(my company have least two diff transpiling format for json-schema, because no body like using this specification)

in before i made [quick & dirty script](https://gist.github.com/d3m3vilurr/034169e6ea137bad24b8cf433cdd93a6) for comparing value of #86
yeah, it's ugly, but we can make clean code.
anyway, current format is simple, so we just need looping and value checking.
(actually we still need value duplication checking, isn't it?)

**Comment by d3m3vilurr** [comment]
my opinion just depend db format, if we will change to more complexly, i don't like personally that changes, but i agree we probably use schema.

so i want to talk just current.

**Comment by devnoname120** [comment]
Hm I agree. This could be kind of overkill, and maybe not worth maintaining.

Anyway I built a rough schema before I saw your answer, so I'll leave it here anyway:
https://gist.github.com/devnoname120/dcef560130a1e3f3dfa109a0fc5b0b2d

**Comment by xyzz** [comment]
https://github.com/vitasdk/vita-headers/issues/83#issuecomment-263103669

**Comment by yifanlu** [comment]
Is this still needed now that we use YAML? Or should this be renamed to "YAML DB validator"?

**Comment by devnoname120** [comment]
No, I'll rename the issue.

I can write a YAML scheme validator if needed, using [https://github.com/Grokzen/pykwalify](pykwalify)

**Comment by xyzz** [comment]
I still think it's useless.

**Comment by devnoname120** [comment]
OK, the benefit with this is that we can catch issues earlier and automatically verify pull requests. A simple python script would let go some issues, and I'm not sure it's less hassle to maintain.
